#!/usr/bin/env python3

# http://inamidst.com/saxo/
# Created by Sean B. Palmer

import re
import time

import saxo
import os

pattern = r"[A-Za-z\x5B-\x60\x7B-\x7D][A-Za-z0-9\x5B-\x60\x7B-\x7D-]{,17}"
regex_nickname = re.compile("^" + pattern + "$")

@saxo.pipe
def tell(arg):
    curr_dir = os.path.dirname(os.path.realpath(__file__))
    to_file = os.path.join(curr_dir, "to")
    with open(to_file) as f:
        code = compile(f.read(), to_file, 'exec')
        exec(code, {'pattern': pattern, 'regex_nickname': regex_nickname})
